-- ============================================
-- 修复 user_vocabulary 表
-- 主要问题：
-- 1. user_id 字段类型应为 UUID（不是 VARCHAR）
-- 2. 应添加外键引用 auth.users
-- 3. RLS 策略应限制为用户自己的数据
-- ============================================

-- 1. 备份现有数据（如果表已存在且有数据）
-- CREATE TABLE IF NOT EXISTS user_vocabulary_backup AS SELECT * FROM user_vocabulary;

-- 2. 删除旧表（如果需要重建）
-- DROP TABLE IF EXISTS user_vocabulary;

-- 3. 重新创建 user_vocabulary 表
CREATE TABLE IF NOT EXISTS user_vocabulary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    word VARCHAR(255) NOT NULL,
    phonetic VARCHAR(255),
    meaning TEXT,
    part_of_speech VARCHAR(50),
    sentence_context TEXT,
    source_sentence_id BIGINT,
    source_article_id BIGINT,
    notes TEXT,
    review_count INT DEFAULT 0,
    next_review_at TIMESTAMP WITH TIME ZONE,
    is_learned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 创建索引
CREATE INDEX IF NOT EXISTS idx_user_vocabulary_user_id ON user_vocabulary(user_id);
CREATE INDEX IF NOT EXISTS idx_user_vocabulary_word ON user_vocabulary(word);
CREATE INDEX IF NOT EXISTS idx_user_vocabulary_next_review ON user_vocabulary(next_review_at) WHERE next_review_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_vocabulary_created_at ON user_vocabulary(created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_vocabulary_user_word_unique 
    ON user_vocabulary(user_id, LOWER(word));

-- 5. 启用 RLS
ALTER TABLE user_vocabulary ENABLE ROW LEVEL SECURITY;

-- 6. 删除旧策略
DROP POLICY IF EXISTS "Users can manage own vocabulary" ON user_vocabulary;
DROP POLICY IF EXISTS "Users can view own vocabulary" ON user_vocabulary;
DROP POLICY IF EXISTS "Users can insert own vocabulary" ON user_vocabulary;
DROP POLICY IF EXISTS "Users can update own vocabulary" ON user_vocabulary;
DROP POLICY IF EXISTS "Users can delete own vocabulary" ON user_vocabulary;

-- 7. 创建正确的 RLS 策略（限制为用户自己的数据）
CREATE POLICY "Users can view own vocabulary" ON user_vocabulary
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own vocabulary" ON user_vocabulary
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own vocabulary" ON user_vocabulary
    FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own vocabulary" ON user_vocabulary
    FOR DELETE USING (auth.uid() = user_id);

-- 8. 更新时间戳触发器
DROP TRIGGER IF EXISTS trigger_update_user_vocabulary_updated_at ON user_vocabulary;
CREATE TRIGGER trigger_update_user_vocabulary_updated_at
    BEFORE UPDATE ON user_vocabulary
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- 9. 验证表结构
SELECT 
    column_name, 
    data_type, 
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'user_vocabulary' 
ORDER BY ordinal_position;
