-- ============================================
-- Supabase 数据库表结构
-- sentences-dictation 项目
-- ============================================

-- 启用 UUID 扩展
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- 1. 文章表 (articles)
-- ============================================
CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    source_url VARCHAR(500),
    source_type VARCHAR(50) DEFAULT 'local',  -- 'local', 'notion', 'new-concept', 'custom'
    cover_image VARCHAR(500),
    total_sentences INT DEFAULT 0,
    metadata JSONB DEFAULT '{}'::jsonb,  -- { difficulty: 1-5, category: 'xxx', tags: [] }
    is_published BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(100) DEFAULT 'system',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 文章索引
CREATE INDEX idx_articles_source_type ON articles(source_type);
CREATE INDEX idx_articles_is_published ON articles(is_published);
CREATE INDEX idx_articles_created_at ON articles(created_at DESC);

-- ============================================
-- 2. 句子表 (sentences)
-- ============================================
CREATE TABLE sentences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    sequence_order INT NOT NULL,
    
    -- 扩展信息 (JSONB)
    extensions JSONB DEFAULT '{}'::jsonb,  -- 详细结构见下方说明
    
    -- 状态管理
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 句子索引
CREATE INDEX idx_sentences_article_id ON sentences(article_id);
CREATE INDEX idx_sentences_sequence_order ON sentences(article_id, sequence_order);
CREATE INDEX idx_sentences_is_active ON sentences(is_active);
CREATE INDEX idx_sentences_content ON sentences USING gin (to_tsvector('english', content));

-- 唯一约束：同一文章内句子序号唯一
CREATE UNIQUE INDEX idx_sentences_article_order_unique 
    ON sentences(article_id, sequence_order) WHERE is_active = TRUE;

-- ============================================
-- 3. 句子扩展信息结构说明
-- extensions JSONB 字段结构：
-- ============================================
/*
{
  "phonetic": "/ðɪs ɪz maɪ bʊk/",           -- 国际音标
  "phonetic_uk": "/ðɪs ɪz maɪ bʊk/",       -- 英式音标
  "phonetic_us": "/ðɪs ɪz maɪ bʊk/",        -- 美式音标
  "translation": "这是我的书",              -- 中文翻译
  "translation_en": "This is my book",     -- 英文释义
  
  "audio_url": "https://...",              -- 音频文件地址
  "audio_speed": 1.0,                      -- 播放速度
  
  "analysis": {                            -- 语法分析
    "grammar_point": "主谓宾结构",
    "structure": "This is my book",
    "notes": ["系表结构", "物主代词用法"]
  },
  
  "vocabulary": [                          -- 词汇列表
    {
      "word": "this",
      "phonetic": "/ðɪs/",
      "meaning": "这",
      "pos": "pron.",  -- 词性
      "examples": ["This is my book", "This is a pen"]
    }
  ],
  
  "tags": ["简单句", "日常用语"],            -- 标签
  "difficulty": 1,                         -- 难度等级 1-5
  
  "notes": "教学笔记...",                  -- 额外笔记
  "memorization_tip": "记忆技巧...",       -- 记忆技巧
  
  "related_sentences": [1, 5, 10],        -- 相关句子ID
  
  "statistics": {                          -- 学习统计
    "practice_count": 0,
    "correct_count": 0,
    "last_practiced_at": null
  }
}
*/

-- ============================================
-- 4. 文章标签表 (tags)
-- ============================================
CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    color VARCHAR(20) DEFAULT '#3B82F6',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 文章-标签关联表
CREATE TABLE article_tags (
    article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (article_id, tag_id)
);

-- ============================================
-- 5. 句子音频表 (sentence_audios) - 可选
-- ============================================
CREATE TABLE sentence_audios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sentence_id BIGINT NOT NULL REFERENCES sentences(id) ON DELETE CASCADE,
    audio_url VARCHAR(500) NOT NULL,
    speaker VARCHAR(100),
    speed DECIMAL(3,2) DEFAULT 1.00,
    duration_ms INT,
    file_size BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 句子音频索引
CREATE INDEX idx_sentence_audios_sentence_id ON sentence_audios(sentence_id);

-- ============================================
-- 6. RLS (Row Level Security) 策略
-- ============================================

ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE sentences ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE sentence_audios ENABLE ROW LEVEL SECURITY;

-- 公开读取权限
CREATE POLICY "Public can read articles" ON articles
    FOR SELECT USING (is_published = TRUE);

CREATE POLICY "Public can read sentences" ON sentences
    FOR SELECT USING (is_active = TRUE);

CREATE POLICY "Public can read tags" ON tags
    FOR SELECT USING (true);

CREATE POLICY "Public can read article_tags" ON article_tags
    FOR SELECT USING (true);

CREATE POLICY "Public can read sentence_audios" ON sentence_audios
    FOR SELECT USING (true);

-- 管理员写入权限（生产环境需要更严格的控制）
CREATE POLICY "Admin can manage articles" ON articles
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Admin can manage sentences" ON sentences
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Admin can manage tags" ON tags
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Admin can manage article_tags" ON article_tags
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Admin can manage sentence_audios" ON sentence_audios
    FOR ALL USING (auth.role() = 'authenticated');

-- ============================================
-- 7. 辅助函数
-- ============================================

-- 更新时间戳的触发器函数
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 更新文章的句子总数
CREATE OR REPLACE FUNCTION update_article_sentence_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        UPDATE articles 
        SET total_sentences = total_sentences - 1 
        WHERE id = OLD.article_id;
        RETURN OLD;
    ELSE
        UPDATE articles 
        SET total_sentences = (
            SELECT COUNT(*) FROM sentences 
            WHERE article_id = NEW.article_id AND is_active = TRUE
        )
        WHERE id = NEW.article_id;
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- 触发器
CREATE TRIGGER trigger_update_articles_updated_at
    BEFORE UPDATE ON articles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trigger_update_sentences_updated_at
    BEFORE UPDATE ON sentences
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trigger_update_sentence_count
    AFTER INSERT OR UPDATE OR DELETE ON sentences
    FOR EACH ROW
    EXECUTE FUNCTION update_article_sentence_count();

-- ============================================
-- 8. 初始化数据示例
-- ============================================

-- 插入示例标签
INSERT INTO tags (name, color) VALUES
    ('简单句', '#10B981'),
    ('复合句', '#F59E0B'),
    ('日常用语', '#3B82F6'),
    ('商务英语', '#6366F1'),
    ('新概念', '#EC4899');

-- 插入示例文章
INSERT INTO articles (title, description, source_type, metadata) VALUES
    ('简单句练习', '基础英语简单句练习', 'local', 
     '{"difficulty": 1, "tags": ["简单句"], "category": "入门"}'::jsonb),
    ('新概念英语第一册', '新概念英语第一册内容', 'new-concept',
     '{"difficulty": 2, "tags": ["新概念"], "category": "教材"}'::jsonb);

-- 插入示例句子
INSERT INTO sentences (article_id, content, sequence_order, extensions) VALUES
    (1, 'Hello, how are you?', 1, 
     '{"phonetic": "/həˈloʊ haʊ ɑːr juː/", "translation": "你好，你好吗？", "difficulty": 1, "tags": ["日常用语"]}'::jsonb),
    (1, 'I am learning English.', 2,
     '{"phonetic": "/aɪ æm ˈlɜːrnɪŋ ˈɪŋglɪʃ/", "translation": "我正在学英语。", "difficulty": 1, "tags": ["简单句"]}'::jsonb),
    (1, 'Practice makes perfect.', 3,
     '{"phonetic": "/ˈpræktɪs meɪks pɜːrˈfekt/", "translation": "熟能生巧。", "difficulty": 2, "tags": ["谚语"]}'::jsonb);

-- 关联标签
INSERT INTO article_tags (article_id, tag_id) VALUES
    (1, 1), (1, 3),
    (2, 5);

-- ============================================
-- 9. 查看表结构
-- ============================================
-- SELECT * FROM information_schema.columns WHERE table_name = 'articles' ORDER BY ordinal_position;
-- SELECT * FROM information_schema.columns WHERE table_name = 'sentences' ORDER BY ordinal_position;
