-- ============================================
-- 完整数据库初始化脚本
-- sentences-dictation 项目
-- 在 Supabase SQL Editor 中执行此脚本
-- ============================================

-- 1. 用户生词本表（使用 UUID 类型与 Supabase auth 匹配）
CREATE TABLE IF NOT EXISTS user_vocabulary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    word VARCHAR(255) NOT NULL,
    phonetic VARCHAR(255),
    meaning TEXT,
    part_of_speech VARCHAR(50),
    sentence_context TEXT,
    source_sentence_id BIGINT,
    source_article_id BIGINT,
    notes TEXT,
    review_count INT DEFAULT 0,
    next_review_at TIMESTAMP WITH TIME ZONE,
    is_learned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_vocabulary_user_id ON user_vocabulary(user_id);
CREATE INDEX IF NOT EXISTS idx_user_vocabulary_word ON user_vocabulary(word);
CREATE INDEX IF NOT EXISTS idx_user_vocabulary_next_review ON user_vocabulary(next_review_at) WHERE next_review_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_vocabulary_created_at ON user_vocabulary(created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_vocabulary_user_word_unique 
    ON user_vocabulary(user_id, LOWER(word));

ALTER TABLE user_vocabulary ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own vocabulary" ON user_vocabulary;
DROP POLICY IF EXISTS "Users can insert own vocabulary" ON user_vocabulary;
DROP POLICY IF EXISTS "Users can update own vocabulary" ON user_vocabulary;
DROP POLICY IF EXISTS "Users can delete own vocabulary" ON user_vocabulary;
CREATE POLICY "Users can view own vocabulary" ON user_vocabulary
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own vocabulary" ON user_vocabulary
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own vocabulary" ON user_vocabulary
    FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own vocabulary" ON user_vocabulary
    FOR DELETE USING (auth.uid() = user_id);

-- 2. 闪卡表
CREATE TABLE IF NOT EXISTS flashcards (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category TEXT DEFAULT '默认',
    tags TEXT[] DEFAULT '{}',
    difficulty INTEGER DEFAULT 3,
    ease_factor DECIMAL DEFAULT 2.5,
    repetition_count INTEGER DEFAULT 0,
    interval_days INTEGER DEFAULT 0,
    next_review_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_flashcards_user_id ON flashcards(user_id);
CREATE INDEX IF NOT EXISTS idx_flashcards_category ON flashcards(category);
CREATE INDEX IF NOT EXISTS idx_flashcards_next_review ON flashcards(next_review_at);

ALTER TABLE flashcards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own flashcards" ON flashcards;
DROP POLICY IF EXISTS "Users can insert own flashcards" ON flashcards;
DROP POLICY IF EXISTS "Users can update own flashcards" ON flashcards;
DROP POLICY IF EXISTS "Users can delete own flashcards" ON flashcards;

CREATE POLICY "Users can view own flashcards" ON flashcards
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own flashcards" ON flashcards
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own flashcards" ON flashcards
    FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own flashcards" ON flashcards
    FOR DELETE USING (auth.uid() = user_id);

-- 3. 学习记录表
CREATE TABLE IF NOT EXISTS flashcard_learning_history (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    flashcard_id UUID NOT NULL REFERENCES flashcards(id) ON DELETE CASCADE,
    correct BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_learning_history_user_id ON flashcard_learning_history(user_id);
CREATE INDEX IF NOT EXISTS idx_learning_history_created_at ON flashcard_learning_history(created_at);

ALTER TABLE flashcard_learning_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own learning history" ON flashcard_learning_history;
DROP POLICY IF EXISTS "Users can insert own learning history" ON flashcard_learning_history;
DROP POLICY IF EXISTS "Users can delete own learning history" ON flashcard_learning_history;

CREATE POLICY "Users can view own learning history" ON flashcard_learning_history
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own learning history" ON flashcard_learning_history
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own learning history" ON flashcard_learning_history
    FOR DELETE USING (auth.uid() = user_id);

-- 4. 更新时间戳函数
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. 触发器
DROP TRIGGER IF EXISTS trigger_update_user_vocabulary_updated_at ON user_vocabulary;
CREATE TRIGGER trigger_update_user_vocabulary_updated_at
    BEFORE UPDATE ON user_vocabulary
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trigger_update_flashcards_updated_at ON flashcards;
CREATE TRIGGER trigger_update_flashcards_updated_at
    BEFORE UPDATE ON flashcards
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();
